---
name: "gerrit-review"
description: "Set review votes on a Gerrit system"

inputs:
  host:
    description: "The Gerrit host with SSH available"
    required: true
  port:
    description: "The SSH port to use. Default 29418"
    required: false
    default: "29418"
  username:
    description: "The username to connect to the Gerrit host as"
    required: true
  key:
    description: "The SSH private key to use"
    required: true
  passphrase:
    description: "The passphrase for the SSH private key"
    required: false
  gerrit-change-number:
    description: "The Gerrit Change Number that is being voted against"
    required: true
  gerrit-patchset-number:
    description: "The patchset number of the change that is being voted against"
    required: false
    default: "1"
  vote-type:
    description: "The type of vote to perform: clear, job_status, default: clear"
    required: false
    default: "clear"

runs:
  using: "composite"
  steps:
    - name: "Clear vote"
      if: ${{ inputs.vote-type == "clear" }}
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        # yamllint disable rule:line-length
        script: |-
          gerrit review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'STARTED: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ' --label Verified=0 --label Code-Review=0 --tag autogenerated:github
        # yamllint enable

    - name: "Success vote"
      if: ${{ inputs.vote-type == "job_status" && success() }}
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        # yamllint disable rule:line-length
        script: |-
          gerrit review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'SUCCESS: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ' --label Verified=1 --label Code-Review=1 --tag autogenerated:github
        # yamllint enable

    - name: "Failure vote"
      if: ${{ inputs.vote-type == "job_status" && failure() }}
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        # yamllint disable rule:line-length
        script: |-
          gerrit review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'FAILURE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ' --label Verified=-1 --label Code-Review=-1 --tag autogenerated:github
        # yamllint enable

    - name: "Cancelled vote"
      if: ${{ inputs.vote-type == "job_status" && cancelled() }}
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        # yamllint disable rule:line-length
        script: |-
          gerrit review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'CANCELLED: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ' --label Verified=-1 --label Code-Review=-1 --tag autogenerated:github
        # yamllint enable
