---
name: "gerrit-review"
description: "Set review votes on a Gerrit system"

inputs:
  host:
    description: "The Gerrit host with SSH available"
    required: true
  port:
    description: "The SSH port to use. Default 29418"
    required: false
    default: "29418"
  username:
    description: "The username to connect to the Gerrit host as"
    required: true
  key:
    description: "The SSH private key to use"
    required: true
  key_name:
    description: "The filename for the key, defaults to id_rsa"
    required: false
    default: "id_rsa"
  known_hosts:
    description: "The known hosts for the host server"
    required: true
  gerrit-change-number:
    description: "The Gerrit Change Number that is being voted against"
    required: true
  gerrit-patchset-number:
    description: "The patchset number of the change that is being voted against"
    required: false
    default: "1"
  vote-type:
    description: "The type of vote to perform: clear, success, failure, cancelled"
    required: false
    default: "clear"

runs:
  using: "composite"
  steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.1
      with:
        key: ${{ inputs.key }}
        name: ${{ inputs.key_name }}
        known_hosts: ${{ inputs.known_hosts }}
        config: |
          Host ${{ inputs.host }}
            User ${{ inputs.username }}
            Port ${{ inputs.port }}
            PubkeyAcceptedKeyTypes +ssh-rsa
            IdentityFile ~/.ssh/${{ inputs.key_name }}

    - name: "Clear vote"
      if: "${{ inputs.vote-type == 'clear' }}"
      shell: bash
      # yamllint disable rule:line-length
      run: |-
        ssh ${{ inputs.host }} gerrit "review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'STARTED: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' --label Verified=0 --label Code-Review=0 --tag autogenerated:github"
      # yamllint enable rule:line-length

    - name: "Success vote"
      if: "${{ inputs.vote-type == 'success' }}"
      shell: bash
      # yamllint disable rule:line-length
      run: |-
        ssh ${{ inputs.host }} gerrit "review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'SUCCESS: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' --label Verified=1 --tag autogenerated:github"
      # yamllint enable rule:line-length

    - name: "Failure vote"
      if: "${{ inputs.vote-type == 'failure' }}"
      shell: bash
      # yamllint disable rule:line-length
      run: |-
        ssh ${{ inputs.host }} gerrit "review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'FAILURE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' --label Verified=-1 --tag autogenerated:github"
      # yamllint enable rule:line-length

    - name: "Cancelled vote"
      if: "${{ inputs.vote-type == 'cancelled' }}"
      shell: bash
      # yamllint disable rule:line-length
      run: |-
        ssh ${{ inputs.host }} gerrit "review ${{ inputs.gerrit-change-number }},${{ inputs.gerrit-patchset-number }} --message 'CANCELLED: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' --label Code-Review=-1 --tag autogenerated:github"
      # yamllint enable rule:line-length
